[programs.localnet]
francoin = "3PXoLHwbQfpwjRB8evrpV8sAqs5LgTvu3HS4SHU2uBN7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/francos/.config/solana/id.json"

[scripts]
test = "node tests/francoin.js"
